# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
name: $(Build.DefinitionName)_$(Build.SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo $'1 we are here\n'
    echo 1.1 we are also here

- script: echo $'2 we are here\n'
    echo 2.1 we are also here\n

- script: echo $'3 we are here\n'
    $'3.1 we are also here\n'
    $'3.2 we are also here'
    3.3 we are also here

- script: echo '$(Build.BuildNumber)'

- script: echo $(Build.BuildNumber)

- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'AzureRmPipeline-conn'
    subscriptionId: '2f106c03-9b32-42ee-be11-99d0286aba1a'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'AzureRmPipeline-rg'
    location: 'West US 2'
    templateLocation: 'Linked artifact'
    csmFile: 'azureresources/azuredeploy.json'
    overrideParameters: '-projectName githubrepo -linkedTemplateUri https://raw.githubusercontent.com/dhorrigan/AzStaticWebsite-repo/master/azureresources/linkedStorageAccount.json'
    deploymentMode: 'Incremental'
    deploymentName: 'DeployPipelineTemplate'

- task: CopyFiles@2
  displayName: 'Copy generated content from $(Build.SourcesDirectory) to $(Build.ArtifactStagingDirectory)'
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)'
    contents: '**/*'
    targetFolder: $(Build.ArtifactStagingDirectory)
    cleanTargetFolder: true

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifacts'
  inputs:
    PathToPublish: '$(Build.ArtifactStagingDirectory)'